apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: selinux1/node-hello-world:latest # Jenkins가 이 부분을 최신으로 갱신
        ports:
        - containerPort: 8080
